game/urls.py
from .views import GameIndexView, GamePlayView

from django.urls import path


app_name = "game"
urlpatterns = [
    path("<int:pk>/", GameIndexView.as_view(), name="index"),
    path("<int:pk>/play/", GamePlayView.as_view(), name="play"),
]

landing/urls.py
from django.urls import path

from . import views

app_name = "landing"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

lobby/urls.py
from .views import IndexView, lobby_view, create_lobby

from django.urls import path


app_name = "lobby"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("<int:pk>", lobby_view, name="lobby"),
    path("create_lobby", create_lobby, name="create_lobby"),
]

powf/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("landing.urls")),
    path("lobby/", include("lobby.urls")),
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("authentication/", include("authentication.urls")),
]

game/models.py
from datetime import datetime
from django.db.models.fields import BooleanField, DateTimeField, IntegerField
from django.db.models.fields.related import ForeignKey
from lobby.models import Lobby
from django.contrib.auth.models import User

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from .settings import MAXIMUM_PLAYERS_PER_GAME


class PokerGame(models.Model):
    lobby_id: models.OneToOneField[Lobby] = models.OneToOneField(
        Lobby, on_delete=models.CASCADE, null=False
    )

    max_players: IntegerField[int] = models.IntegerField(
        default=MAXIMUM_PLAYERS_PER_GAME,
        validators=[
            MaxValueValidator(
                MAXIMUM_PLAYERS_PER_GAME,
                f"Maximum players must be less than {MAXIMUM_PLAYERS_PER_GAME}",
            ),
            MinValueValidator(2, f"Must have at least 2 players"),
        ],
        null=False,
        blank=False,
    )

    start_time: DateTimeField[datetime] = models.DateTimeField(
        name="start time", auto_now=True
    )
    end_time: DateTimeField[datetime | None] = models.DateTimeField(
        name="end time", null=True
    )


class PlayerInGame(models.Model):
    game_id: ForeignKey[PokerGame] = models.ForeignKey(
        PokerGame, on_delete=models.CASCADE
    )
    user_id: ForeignKey[User] = models.ForeignKey(User, on_delete=models.CASCADE)
    chips: IntegerField[int] = models.IntegerField(
        validators=[MinValueValidator(0, "Chips must be a positive value")],
        null=False,
        blank=False,
    )
    is_host: BooleanField[bool] = models.BooleanField()
    last_active: DateTimeField[datetime] = models.DateTimeField(auto_now=True)


class GameResults(models.Model):
    game_id: ForeignKey[PokerGame] = models.ForeignKey(
        PokerGame, on_delete=models.CASCADE
    )
    winner_id: ForeignKey[User] = models.ForeignKey(User, on_delete=models.CASCADE)
    winning_amount: IntegerField[int] = models.IntegerField()

landing/models.py
from django.db import models

# Create your models here.

lobby/models.py
import datetime
from typing import final

from django.db import models
from django.db.models.fields import BooleanField, CharField, DateField, DateTimeField
from django.utils import timezone
from django.contrib import admin
from django.db.models import Count


@final
class Lobby(models.Model):
    lobby_name: CharField[str] = CharField(max_length=20)
    start_date: DateField[datetime.datetime] = DateTimeField(
        "date started", auto_now=True
    )
    is_active: BooleanField[bool] = BooleanField(default=True)

    @admin.display(boolean=True, ordering="start_date", description="Is Lobby Recent")
    def is_lobby_recent(self) -> bool:
        # we do not allow lobbys to be active for more than 1 day
        is_recent: bool = (
            timezone.now()
            >= self.start_date
            >= timezone.now() - datetime.timedelta(days=1)
        )

        return is_recent

lobby/forms.py
from typing import override
from django import forms
from django.core import validators

from game.models import PokerGame

from .models import Lobby


class LobbyForm(forms.ModelForm):
    max_players: forms.IntegerField = forms.IntegerField(label="Max Players")

    class Meta:
        model: type = Lobby
        fields: list[str] = ["lobby_name"]

    @override
    def save(self, commit: bool = True) -> Lobby:
        lobby: Lobby = super().save(commit=commit)

        max_players: int = self.cleaned_data["max_players"]
        if commit:
            _ = PokerGame.objects.create(lobby_id=lobby, max_players=max_players)

        return lobby

game/views.py
from typing import final

from .models import PokerGame, PlayerInGame

from django.views.generic import TemplateView


@final
class GameIndexView(TemplateView):
    template_name = "game/index.html"


@final
class GamePlayView(TemplateView):
    template_name = "game/play.html"

landing/views.py
from typing import final

from django.views.generic import TemplateView


@final
class IndexView(TemplateView):
    template_name = 'landing/index.html'

lobby/views.py
from typing import final, override

from django.contrib.auth.models import AbstractUser, AnonymousUser, User
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages

from game.models import PlayerInGame, PokerGame
from lobby.forms import LobbyForm
from .models import Lobby

from django.views.generic import ListView, TemplateView
from django.utils import timezone
from django.db.models import F, Count


def is_lobby_full(lobby: Lobby) -> bool:
    game: PokerGame = PokerGame.objects.get(id=lobby.pokergame.pk)
    is_full = game.max_players > PlayerInGame.objects.filter(game_id=game).count()

    return is_full


@final
class IndexView(ListView):
    model = Lobby
    template_name: str = "lobby/index.html"

    @override
    def get_context_data(self, **kwargs: str):
        context = super().get_context_data(**kwargs)

        context["lobby_list"] = (
            Lobby.objects.filter(
                start_date__lte=timezone.now(),
                is_active=True,
            )
            .annotate(num_players=Count("pokergame__playeringame"))
            .annotate(max_players=F("pokergame__max_players"))
            .filter(num_players__lt=F("max_players"))
            .order_by("-start_date")[:10]
        )

        return context


def lobby_view(request: HttpRequest, pk: int) -> HttpResponse:
    context = {}

    lobby_id: int = pk
    lobby: Lobby = Lobby.objects.get(id=pk)
    context["lobby_id"] = lobby_id

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("authentication:login"))

    elif not lobby.is_lobby_recent() or not lobby.is_active:
        messages.error(request, "Lobby is expired or invalid")
        return HttpResponseRedirect(reverse("lobby:index"))

    elif not is_lobby_full(lobby):
        messages.error(request, "Lobby is full")
        return HttpResponseRedirect(reverse("lobby:index"))

    return render(request, "lobby/lobby.html", context)


def create_lobby(request: HttpRequest):
    """Handles the lobby creation form"""
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("authentication:login"))

    # if we're getting a POST, create the lobby, otherwise return the form html
    if request.method == "POST":
        form = LobbyForm(request.POST)
        if form.is_valid():
            lobby = form.save()
            return HttpResponseRedirect(reverse("lobby:lobby", args=(lobby.pk,)))
    else:
        form = LobbyForm()

    return render(request, "lobby/index.html", {"form": form})

game/templates/game/play.html
{% extends "base.html" %}
{% load static %}
{% block pokergame %}
    <script type="module" src="{% static 'game/js/index.js' %}"></script>
    <link href="/static/game/css/style.css" rel="stylesheet">
    <div id="app"></div>
{% endblock pokergame %}

landing/templates/landing/index.html
<p>Hello hello hello</p>

lobby/templates/lobby/index.html
{% extends "base.html" %}
{% load static %}
{% block index %}
    {% if lobby_list %}
        <table>
            <tr>
                <th>Lobby Name</th>
                <th>Start Time</th>
                <th>Capacity</th>
                <th>Join</th>
            </tr>
            <ul>
                {% for lobby in lobby_list %}
                    <tr>
                        <td>{{ lobby.lobby_name }}</td>
                        <td>{{ lobby.start_date|timesince }}</td>
                        <td>({{ lobby.pokergame.playeringame_set.count }}/{{ lobby.pokergame.max_players }})</td>
                        <td>
                            <a href="{% url 'lobby:lobby' lobby.pk %}">
                                <button type="text" id="joinbutton">join</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </ul>
        </table>
    {% else %}
        <p>No lobbies are available.</p>
    {% endif %}
    <form action="{% url 'lobby:create_lobby' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create Lobby">
    </form>
{% for message in messages %}
    
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>
           {{ message }}
    </div>

{% endfor %}
{% endblock index %}

lobby/templates/lobby/lobby.html
{% extends "base.html" %}
{% load static %}
{% block lobbylist %}
{{ lobby_id|json_script:"lobby-id" }}

        <div id="user-table">
            <table>
                <tr>
                    <th>Username</th>
                    <th>Chips</th>
                    <th>Is Host</th>
                </tr>
            <tr>
                <td>Getting lobby info...</td>
            </tr>
            </table>
        </div>
        <script src="{% static 'lobby/js/lobby.js' %}"></script>
        
{% endblock lobbylist %}

templates/base.html
<!DOCTYPE html>
{% csrf_token %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>POWF</title>
        <script src="https://unpkg.com/mithril/mithril.js"></script>
    </head>
    <body>
        {% block index %}
        {% endblock index %}
        {% block lobbylist %}
        {% endblock lobbylist %}
        {% block pokergame %}
        {% endblock pokergame %}
    </body>
</html>

templates/index.html
<p>homehomehome</p>